services:
  stirling-pdf:
    image: stirlingtools/stirling-pdf:latest
    container_name: stirling-pdf
    restart: unless-stopped
    volumes:
      - ${DOCKER_DATA_DIR}/stirling-pdf/tessdata:/usr/share/tessdata
      - ${DOCKER_DATA_DIR}/stirling-pdf/configs:/configs
      - ${DOCKER_DATA_DIR}/stirling-pdf/customFiles:/customFiles
      - ${DOCKER_DATA_DIR}/stirling-pdf/pipeline:/pipeline
    environment:
      - TZ=${TZ:-UTC}
      - DOCKER_ENABLE_SECURITY=false
      - SECURITY_ENABLELOGIN=false
      - SYSTEM_MAXFILESIZE=250
      - SYSTEM_FRONTENDURL=https://${STIRLING_PDF_HOSTNAME}
