services:
  mediaflow-proxy:
    image: ghcr.io/mhdzumair/mediaflow-proxy-light:latest
    container_name: mediaflow-proxy
    restart: unless-stopped
    expose:
      - "8888"
    environment:
      - APP__AUTH__API_PASSWORD=${MEDIAFLOW_API_PASSWORD}
      - APP__PROXY__PROXY_URL=http://warp:1080
      - APP__PROXY__ALL_PROXY=true
    depends_on:
      warp:
        condition: service_healthy
    stop_grace_period: 10s
    logging:
      driver: json-file
      options:
        max-size: "5m"
        max-file: "2"
    deploy:
      resources:
        limits:
          memory: 96M
        reservations:
          memory: 32M
