[server]
host = "0.0.0.0"
port = 8888

[proxy]
proxy_url = ""

[proxy.transport_routes]
"all://*.strem.fun" = { proxy = true, proxy_url = "http://warp:1080", verify_ssl = true }
"all://sooti.click" = { proxy = true, proxy_url = "http://warp:1080", verify_ssl = true }