services:
  honey:
    image: ghcr.io/dani3l0/honey:latest
    container_name: honey
    restart: unless-stopped
    user: "${PUID}:${PGID}"
    volumes:
      - ./config.json:/app/dist/config/config.json:ro
      - ${DOCKER_DATA_DIR}/honey:/app/dist/img/custom
    environment:
      - TZ=${TZ:-UTC}
