services:
  mediafusion-api:
    image: mhdzumair/mediafusion:latest
    container_name: mediafusion-api
    restart: unless-stopped

    environment:
      - TZ=${TZ:-UTC}
      - HOST_URL=https://${MEDIAFUSION_HOSTNAME}
      - POSTGRES_URI=postgresql://mediafusion:${MEDIAFUSION_POSTGRES_PASSWORD}@mediafusion-postgres:5432/mediafusion
      - REDIS_URL=redis://mediafusion-redis:6379/0
      - SECRET_KEY=${MEDIAFUSION_SECRET_KEY}
      - API_PASSWORD=${MEDIAFUSION_API_PASSWORD}
      - CONTACT_EMAIL=admin@${DOMAIN}
    depends_on:
      - mediafusion-postgres
      - mediafusion-redis


  mediafusion-worker:
    image: mhdzumair/mediafusion:latest
    container_name: mediafusion-worker
    command: ["/usr/local/bin/mediafusion-worker"]
    restart: unless-stopped
    environment:
      - TZ=${TZ:-UTC}
      - HOST_URL=https://${MEDIAFUSION_HOSTNAME}
      - POSTGRES_URI=postgresql://mediafusion:${MEDIAFUSION_POSTGRES_PASSWORD}@mediafusion-postgres:5432/mediafusion
      - REDIS_URL=redis://mediafusion-redis:6379/0
      - SECRET_KEY=${MEDIAFUSION_SECRET_KEY}
      - API_PASSWORD=${MEDIAFUSION_API_PASSWORD}
      - CONTACT_EMAIL=admin@${DOMAIN}
    depends_on:
      - mediafusion-postgres
      - mediafusion-redis
      - mediafusion-api


  mediafusion-postgres:
    image: postgres:17-alpine
    container_name: mediafusion-postgres
    restart: unless-stopped
    volumes:
      - ${DOCKER_DATA_DIR}/mediafusion/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=mediafusion
      - POSTGRES_USER=mediafusion
      - POSTGRES_PASSWORD=${MEDIAFUSION_POSTGRES_PASSWORD}



  mediafusion-redis:
    image: redis:alpine
    container_name: mediafusion-redis
    restart: unless-stopped

    stop_grace_period: 5s

