services:
  comet:
    image: g0ldyy/comet:latest
    container_name: comet
    restart: unless-stopped

    volumes:
      - ${DOCKER_DATA_DIR}/comet:/app/data
    environment:
      - TZ=${TZ:-UTC}
      - DATABASE_TYPE=sqlite
      - DATABASE_PATH=/app/data/comet.db
      - FASTAPI_PORT=2020
      - ADMIN_DASHBOARD_PASSWORD=${COMET_ADMIN_DASHBOARD_PASSWORD:-CHANGE_ME}
      - PROXY_DEBRID_STREAM_PASSWORD=${COMET_PROXY_DEBRID_STREAM_PASSWORD:-CHANGE_ME}
      - PUBLIC_BASE_URL=https://${COMET_HOSTNAME}
      - SCRAPE_TORRENTIO=${COMET_SCRAPE_TORRENTIO:-False}
      - SCRAPE_AIOSTREAMS=${COMET_SCRAPE_AIOSTREAMS:-False}
      - AIOSTREAMS_URL=${COMET_AIOSTREAMS_URL:-}
      - SCRAPE_NYAA=${COMET_SCRAPE_NYAA:-False}
      - SCRAPE_ANIMETOSHO=${COMET_SCRAPE_ANIMETOSHO:-False}
      - SCRAPE_TORRENTSDB=${COMET_SCRAPE_TORRENTSDB:-False}
      - SCRAPE_PEERFLIX=${COMET_SCRAPE_PEERFLIX:-False}


