services:
  comet:
    image: g0ldyy/comet:latest
    container_name: comet
    restart: unless-stopped

    volumes:
      - ${DOCKER_DATA_DIR}/comet:/app/data
    environment:
      - TZ=${TZ:-UTC}
      - DATABASE_TYPE=sqlite
      - DATABASE_PATH=/app/data/comet.db
      - FASTAPI_PORT=2020


