[uwsgi]
exec-pre = python /app/scripts/wait_for_redis.py

attach-daemon = redis-server /etc/dispatcharr/redis.conf
attach-daemon = nice -n $(CELERY_NICE_LEVEL) celery -A dispatcharr worker -Q celery -n default@%%h --concurrency=1
attach-daemon = nice -n $(CELERY_NICE_LEVEL) celery -A dispatcharr worker -Q dvr -n dvr@%%h --pool=threads --concurrency=1
attach-daemon = nice -n $(CELERY_NICE_LEVEL) celery -A dispatcharr beat
attach-daemon = daphne -b 0.0.0.0 -p 8001 dispatcharr.asgi:application

chdir = /app
module = dispatcharr.wsgi:application
virtualenv = /dispatcharrpy
master = true
env = DJANGO_SETTINGS_MODULE=dispatcharr.settings
env = USE_NGINX_ACCEL=true
socket = /app/uwsgi.sock
chmod-socket = 777
vacuum = true
die-on-term = true
static-map = /static=/app/static

workers = 1
cheaper = 0
socket-timeout = 600
buffer-size = 32768
max-requests = 500
reload-on-rss = 192
lazy-apps = true

gevent = 100
gevent-early-monkey-patch = true
import = dispatcharr.gevent_patch

thunder-lock = true

log-4xx = true
log-5xx = true
disable-logging = false
log-master = true
logformat-strftime = true
log-date = %%Y-%%m-%%d %%H:%%M:%%S,000
log-format = %(ftime) $(DISPATCHARR_LOG_LEVEL) uwsgi.requests Worker ID: %(wid) %(method) %(status) %(uri) %(msecs)ms
log-buffering = 1024